-- Datas for Integration Tests purpose --

-- Roles
INSERT INTO ROLE (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (NAME) VALUES ('ROLE_USER');

-- Users
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, BIRTH_DATE, INSCRIPTION_DATE, PASSWORD)
VALUES ('Admin', 'Admin', 'admin', 'admin@example.com', '1988-03-02', '2024-01-01', '$2a$10$n15EyxawFS7VJYgPf6a5.uLB35S1vWxmow/psJW5NLfWOT93Uvm7a'); -- pwd1234

-- User Roles
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
